server:
  port: 8080
spring:
  application:
    name: admin-template-with-simple
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin-template-simple?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
redis.type: embedded
captcha:
  prefix: behavior-captcha
  expire:
    default: 10000
    WORD_IMAGE_CLICK: 20000
  init-default-resource: true
  local-cache-enabled: true
  local-cache-size: 20
  local-cache-wait-time: 5000
  local-cache-period: 2000
  font-path:
    - classpath:captcha/font/SourceHanSansSC-Normal.otf
  secondary:
    enabled: false
    expire: 120000
    keyPrefix: "behavior-captcha:secondary"
web:
  exception:
    template: '{"code":"#{code}","message":"#{message}"}'
